install:
  # g++
  - set PATH=%PATH%;C:\MinGW\bin
  # qmake
  - set QTDIR=C:\Qt\5.5\mingw492_32
  - set PATH=%PATH%;%QTDIR%\bin
  # Boost
  - set PATH=%PATH%;C:\Libraries\boost_1_63_0

build_script:
  - qmake
  - mingw32-make
  - cd release
  - start /b appveyor_qmake_gcc_cpp14_boost_qt5.exe
  - timeout 10
  - taskkill /f /im appveyor_qmake_gcc_cpp14_boost_qt5.exe